workflows:
  flutter_python_build:
    name: Flutter + Python Build
    environment:
      flutter: stable
    scripts:
      - echo "🚀 Checking Flutter Version..."
      - flutter --version
      - echo "🔥 Running Flutter Pub Get..."
      - flutter pub get
      - echo "⚡ Running Python Script..."
      - python3 FLASH.py
      - echo "📱 Building Flutter APK..."
      - flutter build apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
